auth:
  default-pwd: 123456 #重置密码的默认密码
spring:
  application:
    name: auth-service
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/roses?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
  aop:
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/roses/auth/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.roses.auth.modular.entity
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
logging:
  level.root: info
  level.com.iciyun: debug
  path: logs/
  file: roses-order.log

server:
  port: 3333
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3 #客户端向注册中心发送心跳的时间
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    registry-fetch-interval-seconds: 3  #获取服务的刷新时间
