server:
  port: 11001

spring:
  application:
    name: roses-account
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_account?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

mybatis-plus:
  typeAliasesPackage: com.stylefeng.roses.account.modular.entity

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: roses-account.log

eureka:
  instance:
    prefer-ip-address: true #将IP注册到eureka
    lease-renewal-interval-in-seconds: 3 #客户端向注册中心发送心跳的时间
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 3  #获取服务的刷新时间
