server:
  port: 5555

develop:
  open: true          #是否开启开发者模式,开启则开启DevelopFilter,走接口不用传jwt token
  user-id: 1          #开发环境下,传给下游服务的当前用户id,默认为1

jwt:
  header: Authorization     #http请求头所需要的字段
  secret: mySecret          #jwt秘钥
  expiration: 604800        #7天 单位:秒
  auth-path: /auth          #认证请求的路径

spring:
  application:
    name: roses-gateway

zuul:
  add-host-header: true
  routes:
    roses-auth: /roses-auth/**
    api-gate:
      path: /login/**
      url: forward:/login  #以/login开头的请求转发到本网关的控制器
  retryable: false   #转发重试关闭

feign:
  hystrix:
    enabled: true

ribbon:
  connect-imeout: 300 #创建连接的超时时间 300毫秒
  read-timeout: 1000 #处理请求的超时时间 1秒
  max-auto-retries-next-server: 2 #切换实例的重试次数
  max-auto-retries: 1 #对当前实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000   #hystrix线程超过3秒熔断，数值大于ribbon的处理超时时间，留给ribbon重试，否则直接熔断，重试就没有意义了
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://stylefeng:123456@www.roses1.com:8761/eureka
    registry-fetch-interval-seconds: 30
