develop:
  open: true          #是否开启开发者模式,开启则开启DevelopFilter,走接口不用传jwt token
  user-id: 1          #开发环境下,传给下游服务的当前用户id,默认为1

jwt:
  header: Authorization     #http请求头所需要的字段
  secret: mySecret          #jwt秘钥
  expiration: 604800        #7天 单位:秒
  auth-path: /auth          #认证请求的路径

spring:
  application:
    name: roses-gateway

zuul:
  add-host-header: true
  routes:
    roses-auth: /roses-auth/**
    api-gate:
      path: /login/**
      url: forward:/login  #以/login开头的请求转发到本网关的控制器
  retryable: false   #转发重试关闭

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000   #转发超时时间 5秒
ribbon:
  connect-imeout: 2000 #创建连接的超时时间 2秒
  read-timeout: 5000 #路由转发请求的超时时间 5秒

server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://www.roses1.com:8761/eureka,http://www.roses2.com:8762/eureka
    registry-fetch-interval-seconds: 3  #获取服务的刷新时间