spring:
  application:
    name: eureka-server
  profiles:
    active: peer2
---

spring:
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: www.peer1.com
  client:
    register-with-eureka: false  #false 让服务注册中心不注册自己
    fetch-registry: false #false 让服务注册中心不注册自己
    serviceUrl:
     defaultZone: http://www.peer2.com:1112/eureka/

---

spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: www.peer2.com
  client:
    register-with-eureka: false  #false 让服务注册中心不注册自己
    fetch-registry: false #false 让服务注册中心不注册自己
    serviceUrl:
     defaultZone: http://www.peer1.com:1111/eureka/








