spring:
  application:
    name: eureka-server
  profiles:
    active: peer1
eureka:
  server:
    enable-self-preservation: false #是否开启自我保护（运行期间spring会统计信条失败的比例在15分钟之内是否低于85%，如果不低于85%，Eureka会将实例注册信息保护起来，让这些实例不会过期）
    renewal-percent-threshold: 0.49
  client:
    register-with-eureka: false  #false 让服务注册中心不注册自己
    fetch-registry: false #false 让服务注册中心不注册自己
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 2
---

spring:
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: www.peer1.com
    serviceUrl:
     defaultZone: http://www.peer2.com:1112/eureka/

---

spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: www.peer2.com
  client:
    serviceUrl:
     defaultZone: http://www.peer1.com:1111/eureka/








