server:
  port: 8002

spring:
  application:
    name: roses-config
  profiles:
    active: @spring.active@

management:
  security:
    enabled: false

---

spring:
  profiles: local
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://gitee.com/naan1993/roses-config.git
          username: xxxx
          password: xxxx
          search-paths: /**

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://gitee.com/naan1993/roses-config.git
          username: xxxx
          password: xxxx
          search-paths: /**

share:
  log:
    path: /usr/local/app/config-server

---

spring:
  profiles: produce
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://gitee.com/naan1993/roses-config.git
          username: xxxx
          password: xxxx
          search-paths: /**

share:
  log:
    path: /usr/local/app/config-server
