spring:
  application:
    name: roses-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/naan1993/roses-config
          search-paths: roses-configs
          username:
          password:
server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3 #客户端向注册中心发送心跳的时间
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    registry-fetch-interval-seconds: 3  #获取服务的刷新时间

